<?php

namespace Fabiom\UglyDuckling\Framework\Routing;

/**
 * Holds the route entries generated by RouteTableGenerator (see bin/ud-routes),
 * loaded once at bootstrap via load().
 */
final class RouteTable {

    private static array $byName = [];
    private static array $bySlug = [];

    public static function load(string $path): void {
        self::$byName = require $path;
        self::$bySlug = [];
        foreach (self::$byName as $entry) {
            self::$bySlug[$entry['slug']] = $entry;
        }
    }

    public static function get(string $name): array {
        if (!isset(self::$byName[$name])) {
            throw new \InvalidArgumentException("Undefined route: '$name'");
        }
        return self::$byName[$name];
    }

    public static function forSlug(string $slug): array {
        if (!isset(self::$bySlug[$slug])) {
            throw new \InvalidArgumentException("No route matches slug: '$slug'");
        }
        return self::$bySlug[$slug];
    }

}
